# Terraform configuration for zero_trust_security
## Resources in this module:
# cloudflare_zero_trust_access_application
# cloudflare_zero_trust_access_custom_page
# cloudflare_zero_trust_access_group
# cloudflare_zero_trust_access_identity_provider
# cloudflare_zero_trust_access_infrastructure_target
# cloudflare_zero_trust_access_key_configuration
# cloudflare_zero_trust_access_policy
# cloudflare_zero_trust_access_service_token
# cloudflare_zero_trust_access_short_lived_certificate
# cloudflare_zero_trust_access_tag
# cloudflare_zero_trust_device_custom_profile
# cloudflare_zero_trust_device_managed_networks
# cloudflare_zero_trust_device_posture_integration
# cloudflare_zero_trust_device_posture_rule
# cloudflare_zero_trust_dlp_custom_profile
# cloudflare_zero_trust_dlp_dataset
# cloudflare_zero_trust_dlp_entry
# cloudflare_zero_trust_dlp_predefined_profile
# cloudflare_zero_trust_gateway_certificate
# cloudflare_zero_trust_gateway_logging
# cloudflare_zero_trust_gateway_policy
# cloudflare_zero_trust_gateway_proxy_endpoint
# cloudflare_zero_trust_gateway_settings
# cloudflare_zero_trust_list
# cloudflare_zero_trust_organization
# cloudflare_zero_trust_risk_behavior
# cloudflare_zero_trust_risk_scoring_integration
# cloudflare_zero_trust_tunnel_cloudflared
# cloudflare_zero_trust_tunnel_cloudflared_config
# cloudflare_zero_trust_tunnel_cloudflared_route
# cloudflare_zero_trust_tunnel_cloudflared_virtual_network

